server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "qa"
build:
  info: "3.0"
accounts:
  message: "Welcome to e-Bank accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@ebank.com"
  onCallSupport:
    - +1 5052909253
    - +1 4724906961