build:
  info: "2.0"
accounts:
  message: "Welcome to e-Bank loans related QA APIs"
  contactDetails:
    name: "Paulo César - QA Lead"
    email: "pysllo@ebank.com"
  onCallSupport:
    - +55 64926194518
    - +55 2774363571

