build:
  info: "3.0"
accounts:
  message: "Welcome to e-Bank loans related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@ebank.com"
  onCallSupport:
    - +1 5052909253
    - +1 4724906961